authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication'
urlpatterns = [

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),

]

iqgame/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# from .views import start_view
from authentication.views import start_view


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include('authentication.urls')),
    url(r'^quiz/', include('quiz.urls')),
    url(r'^$', start_view, name='landing'),
]

quiz/urls.py
from django.conf.urls import url

from . import views

app_name = 'quiz'
urlpatterns = [

    url(r'^answer$', views.handle_user_answer, name='handle_answer'),
    url(r'^question$', views.render_next_question, name='next_question'),
    url(r'^new_game', views.start_new_game, name='new_game'),
    url(r'^$', views.start, name='start'),

]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from quiz.models import Question

# Create your models here.


class User(AbstractUser):
    questions = models.ManyToManyField(Question, blank=True)

authentication/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import get_user_model
User = get_user_model()


class CustomUserLoginForm(AuthenticationForm):
    model = User
    # TODO - need to provide error message when no user is found


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    email = forms.EmailField(label='Email address', widget=forms.EmailInput)

    class Meta(UserCreationForm.Meta):
        model = User

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('This email is already signed up!')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match!')
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

authentication/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect

from django.shortcuts import render, redirect
from django.contrib import auth
from .forms import CustomUserCreationForm
from django.urls import reverse


def start_view(request):
    context = dict()
    error_message = request.session.get('login_error')
    if error_message:
        context['login_error'] = error_message
    context['username'] = auth.get_user(request).username
    context['form'] = CustomUserCreationForm()
    return render(request, 'authentication/main.html', context)


def login(request):
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
        else:
            request.session['login_error'] = 'Login and/or password are incorrect'
    return HttpResponseRedirect(reverse('landing'))


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('landing'))


def register(request):
    context = dict()
    context['form'] = CustomUserCreationForm()
    if request.POST:
        new_user_form = CustomUserCreationForm(request.POST)
        context['form'] = new_user_form
        if new_user_form.is_valid():
            user = new_user_form.save()
            print(user)
            new_user = auth.authenticate(username=new_user_form.cleaned_data['username'],
                                         password=new_user_form.cleaned_data['password2'])
            auth.login(request, new_user)
            return HttpResponseRedirect(reverse('landing'))
        else:
            context['form'] = new_user_form
    return render(request, 'authentication/main.html', context)

authentication/templates/authentication/main.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Landing page</title>
    <link rel="stylesheet" href="{% static 'authentication/css/foundation.css' %}"/>
    <link rel="stylesheet" href="{% static 'authentication/css/base.css' %}?v=00008"/>
    <style>
        body{
            background: url('{% static "authentication/background.jpg" %}');
		    background-size: cover;
        }
    </style>
</head>
<script
  src="http://code.jquery.com/jquery-1.9.1.js"
  integrity="sha256-e9gNBsAcA0DBuRWbm0oZfbiCyhjLrI6bmqAl5o+ZjUA="
  crossorigin="anonymous"></script>
<body>
    <div id="entry">
        <div id="entry-tagline">Play and study</div>
        <div id="entry-description">It will be better soon</div>
        <a href="{% url 'quiz:start' %}"><button class="button" id="button-without-register">Play without signing up</button></a>
    </div>

    <div id="auth">

    {% if not username %}
        <button id="show-registration-form" class="label round secondary">Registration</button>
        <button id="show-login-form" class="label round secondary">Login</button>
        <div id="auth-form">
            <div id="login" class="small-offset-2 small-8 columns">
                <form action='{% url "authentication:login" %}' method="post">
                    {% csrf_token %}
                    <label for="username">Username:</label>
                    <input type="text" name="username" id="username">
                    <label for="password">Password:</label>
                    <input type="password" name="password" id="password">
                    {% if login_error %}
                        <label class="error">{{ login_error }}</label>
                    {% endif %}
                    <input class="button" type="submit" value="Sign IN">
                </form>
            </div>
            <div id="register" class="small-offset-2 small-8 columns">
                <form action="{% url 'authentication:register' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input class="button" type="submit" value="Sign UP">
                </form>
            </div>
        </div>
    {% endif %}

    {% if username %}
        <a href="{% url 'authentication:logout' %}"><button id="logout" class="label round secondary">Logout</button></a>
        <a href="{% url 'quiz:start' %}"><div id=start>Start game!</div></a>
    {% endif %}

    </div>

    <script src="{% static 'authentication/js/index.js' %}?v=00004"></script>
</body>
</html>