iqgame/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# from .views import start_view
from authentication.views import start_view


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include('authentication.urls')),
    url(r'^quiz/', include('quiz.urls')),
    url(r'^$', start_view, name='landing'),
]

quiz/urls.py
from django.conf.urls import url

from . import views

app_name = 'quiz'
urlpatterns = [

    url(r'^answer$', views.handle_user_answer, name='handle_answer'),
    url(r'^question$', views.render_next_question, name='next_question'),
    url(r'^new_game', views.start_new_game, name='new_game'),
    url(r'^$', views.start, name='start'),

]

quiz/models.py
import datetime
from django.utils import timezone
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.answer_text

quiz/views.py
# -*- coding: UTF-8 -*-

from random import Random
import json

#from django.core.serializers import serialize
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect, ensure_csrf_cookie

from .models import Question

DIFFICULTY = 50


def start(request):
    numbers = {question.pk for question in Question.objects.all()}
    question_to_render = Random().sample(numbers, 1)[0]

    #because Set is non-serializable
    request.session['non_seen'] = list(numbers - {question_to_render})
    request.session['current'] = question_to_render
    request.session['seen'] = [question_to_render]
    request.session['user_score'] = 0
    request.session['computer_score'] = 0

    context = dict()
    context['user_score'] = 0
    context['computer_score'] = 0
    context['question'] = Question.objects.get(pk=question_to_render)
    context['answers'] = context['question'].answer_set.all().order_by('?')

    return render(request, 'quiz/index.html', context)


@ensure_csrf_cookie
def handle_user_answer(request):
    if request.body:
        question_number = request.session.get('current')
        current_question_instance = Question.objects.get(pk=question_number)

        response = dict()

        received_data = json.loads(request.body.decode("utf-8"))
        user_answer = int(received_data.get('answer'))
        correct_answer_pk = current_question_instance.answer_set.get(is_correct=True).pk

        response['correct_answer'] = correct_answer_pk
        response['user_answer'] = user_answer
        if correct_answer_pk == user_answer:
            request.session['user_score'] += 1
            response['is_user_correct'] = True
        else:
            response['is_user_correct'] = False

        difficulty = received_data.get('level')
        print(difficulty)
        if is_computer_correct(difficulty):
            response['computer_answer'] = correct_answer_pk
            response['is_computer_correct'] = True
            request.session['computer_score'] += 1
        else:
            response['computer_answer'] = return_wrong_answer(current_question_instance)
            response['is_computer_correct'] = False

        response['user_score'] = request.session['user_score']
        response['computer_score'] = request.session['computer_score']

        return JsonResponse(response)


def render_next_question(request):
    numbers = request.session.get('non_seen')
    if len(numbers) == 0:
        numbers = {question.pk for question in Question.objects.all()}

    question_number_to_render = None
    while True:
        question_number_to_render = Random().sample(numbers, 1)[0]
        if not Question.objects.filter(pk=question_number_to_render).exists():
            numbers -= {question_number_to_render}
        else:
            break
    current_question_instance = Question.objects.get(pk=question_number_to_render)

    request.session['non_seen'] = list(set(numbers) - {question_number_to_render})
    request.session['current'] = question_number_to_render

    context = dict()
    context['user_score'] = request.session['user_score']
    context['computer_score'] = request.session['computer_score']
    context['question'] = current_question_instance
    context['answers'] = context['question'].answer_set.all().order_by('?')

    return render(request, 'quiz/index.html', context)


def start_new_game(request):
    return HttpResponseRedirect(reverse('quiz:start'))


def is_computer_correct(difficulty):
    if Random().randint(0, 99) < difficulty:
        return True


def return_wrong_answer(question):
    for answer in question.answer_set.all():
        if not answer.is_correct:
            return answer.pk

quiz/templates/quiz/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>QUIZ</title>

    <link rel="stylesheet" href='{% static "quiz/css/base.css" %}?v=000113'/>
    <script
  src="http://code.jquery.com/jquery-1.9.1.js"
  integrity="sha256-e9gNBsAcA0DBuRWbm0oZfbiCyhjLrI6bmqAl5o+ZjUA="
  crossorigin="anonymous"></script>
    <style>
        .computer-answer:after {
		    content: "";
		    width: 70px;
		    height: 70px;
		    background: url('{% static "quiz/icons/laptop.png" %}');
		    background-size: cover;
		    top: 5px;
		    right: -90px;
		    position: absolute;
		    display: inline-block;
		}

		.human-answer:before {
		    content: "";
		    width: 70px;
		    height: 70px;
		    background: url('{% static "quiz/icons/human.png" %}');
		    background-size: cover;
		    top: 5px;
		    left: -90px;
		    position: absolute;
		    display: inline-block;
		}
    </style>
</head>
<body>
	<div id="wrapper">
		<div id="score">
            <div id="user-score-left">{{ user_score }}</div>
			<div id="user-score"></div>
			<div id="computer-score"></div>
            <div id="computer-score-right">{{ computer_score }}</div>
		</div>

		<div id="difficulty" class="mobile-app-toggle" data-mobile-app-toggle>
			<p id="dif-tooltip">Choose difficulty level:</p>
			<div>
                <button id="b-1" class="button is-active">Easy</button>
				<button id="b-2" class="button">Medium</button>
				<button id="b-3" class="button">Hard</button>
                <div id="b-change">Change</div>
            </div>
		</div>

		<div id="quiz">
			<h3 id="quiz-title">{{ question.question_text }}</h3>
			{% for answer in answers %}
				<div class="answer" id="{{ answer.pk }}">
					<div class="answer-text">
						{{ answer.answer_text }}
					</div>
				</div>
			{% endfor %}
			<button id="next" disabled>Next=></button>
            <a href="{% url 'quiz:new_game' %}"><button id="new-game">New Game</button></a>
		</div>
    </div>
    <script>
		let handleAnswerUrl = "{% url 'quiz:handle_answer' %}";
        let questionUrl = "{% url 'quiz:next_question' %}"
    </script>
    <script src="{% static "quiz/js/main.js" %}"></script>
</body>
</html>